### PR TITLE
Add dockerfile for building namerctl image

### PR DESCRIPTION
**Pull request by klingerf**
Am updating the repo with a Dockerfile, so that we can start publishing a `buoyantio/namerctl` image to docker hub. In the process I had to vendor all of the project's go dependencies, which is the bulk of this change.

My plan, after this merges, is to release namerctl by creating a new git tag, uploading the exec files to the github release, and publishing the docker image to docker hub. What should the new release version be? `0.8.6`? The only release for this project so far is `0.7.3`, which makes me think it follows namerd versioning.

### CODE REVIEW

**Comment by olix0r** [comment]
I'm going to move linkerd images over to the 'linkerd' organization.  Can we just do that now/here? https://hub.docker.com/u/linkerd/

**Comment by olix0r** [comment]
Wow how did so many dependencies get added to namerctl? Nothing in namerctl should, as far as I can tell, require things like fsnotify.  Where does this all come from?

**Comment by olix0r** [comment]
Ah, I bet this all comes from Viper...  wild.

**Comment by olix0r** [comment]
One last thing: I'm continually confused and intimidated by the plethora of go vendoring tools.  Can you make sure that a README (find if it's vendor/README) includes some description of how to modify dependencies in the repo?

**Comment by klingerf** [comment]
@olix0r Cool, yep, all makes sense -- have updated in the latest commit.

**Pull request merged**
